# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "puchi_ble_v1" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: puchi_ble_v1
#     shield: reviung41
#
---
include:
  - board: puchi_ble_v1
    shield: corne_left
  - board: puchi_ble_v1
    shield: corne_right
  - board: puchi_ble_v1
    shield: settings_reset
